from command import *

class HelpHelp(Command):
    @staticmethod
    def execute():
        command_table = PrettyTable()
        command_table.field_names = ['Команда', 'Функционал']
        command_table.add_row(['path <version>', 'Выводит путь до библиотек'])
        command_table.add_row(['', 'для указанной версии Lazurite.'])
        command_table.add_row(['', ''])
        command_table.add_row(['path <version> <path>', 'Устанавливает путь до библиотек'])
        command_table.add_row(['', 'для указанной версии Lazurite.'])
        command_table.add_row(['', ''])
        command_table.add_row(['paths', 'Таблица с путями до библиотек'])
        command_table.add_row(['', 'для всех версий Lazurite.'])
        command_table.add_row(['---', '---'])
        command_table.add_row(['lazurite version', 'Выводит основную версию Lazurite.'])
        command_table.add_row(['lazurite version <version>', 'Изменяет основную версию Lazurite.'])
        command_table.add_row(['---', '---'])
        command_table.add_row(['install <name>', 'Устанавливает библиотеку.'])
        command_table.add_row(['update <name>', 'Обновляет библиотеку.'])
        command_table.add_row(['delete <name>', 'Удаляет библиотеку.'])
        command_table.add_row(['---', '---'])
        command_table.add_row(['outdated', 'Таблица со всеми библиотеками,'])
        command_table.add_row(['', 'доступными для обновления.'])
        command_table.add_row(['', ''])
        command_table.add_row(['updateall', 'Обновляет все необновлённые'])
        command_table.add_row(['', 'библиотеки до последней версии.'])
        command_table.add_row(['---', '---'])
        command_table.add_row(['list', 'Таблица со всеми'])
        command_table.add_row(['', 'установленными библиотеками.'])
        command_table.add_row(['', ''])
        command_table.add_row(['info <name>', 'Информация о установленной библиотеке.'])
        command_table.add_row(['---', '---'])
        command_table.add_row(['title <text>', 'Устанавливает заголовок окна.'])
        command_table.add_row(['clear', 'Отчищает консоль.'])
        command_table.add_row(['---', '---'])
        command_table.add_row(['help', 'Таблица со всеми командами.'])
        print(command_table)
